### ISSUE TITLE
'glulx entry points.i7x' extension causes failure on Inform 7 build 6M62

### ISSUE THREAD

**Issue by BroadcastGames** [I7-Standard-Examples/Bronze#3]
Hello,

I have been able to get all of these I7-Standard-Examples to run on Inform 7 except Bronze.  I pulled the extension from: https://github.com/i7/extensions/blob/master/Emily%20Short/Glulx%20Entry%20Points.i7x

The extension seems to have been modified two weeks ago. Is that perhaps the issue?  I did attempt the previous two commits of that extension with errors resulting each time.  Thank you.

**Comment by ShinSekaiNoKami** [comment]
Since that extension is not used by Bronze, I don't understand how your issue arose. The required extensions are in the repositories.  :)

**Comment by BroadcastGames** [comment]
Bronze has this on line 3303 https://github.com/I7-Standard-Examples/Bronze/blob/master/Bronze.inform/Source/story.ni#L3303:

    Include Flexible Windows by Jon Ingold.

https://github.com/i7/extensions/blob/master/Jon%20Ingold/Flexible%20Windows.i7x

Which inside that extension, on line 19, it does require the extension:

   Include version 10/160919 of Glulx Entry Points by Emily Short.

These were seemingly updated 3 days ago, and I'm uncertain how to proceed in resolving the issue of getting Bronze to work in Inform 7.

**Comment by ShinSekaiNoKami** [comment]
Oops. My bad. I should have put them in the extensions directory. I'll try to trace the correct versions.

**Comment by ShinSekaiNoKami** [comment]
Please confirm this fixes your problem.

**Comment by BroadcastGames** [comment]
Fix confirmed. Thank you.
